apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-micro-project
  labels:
    app: node-svr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-svr
  template:
    metadata:
      labels:
        app: node-svr
    spec: 
      containers:
      - name: app-ctr
        image: rafik1212/k8s-microproject:latest
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: k8-map
        volumeMounts:
        - name: k8s-node-persistent-storage
          mountPath: /mnt/app
      volumes:
      - name: k8s-node-persistent-storage
        persistentVolumeClaim:
          claimName: k8-pvc
