apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  labels:
    type: local
    app: app
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
