apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeName: pv-data
